---
- name: Swapfile | test for swap partition
  shell: swapon -s | grep -E '^/'
  sudo: yes
  register: swapfile
  ignore_errors: yes

- name: write swapfile
  when: swapfile|failed
  sudo: yes
  command: >
    fallocate -l {{ swap_size }} {{ swap_file }}
    creates={{ swap_file }}
  register: write_swapfile

- name: set swapfile permissions
  when: swapfile|failed and write_swapfile.changed
  file: path={{ swap_file }}
        owner=root
        group=root
        mode=0600

- name: prepare swapfile
  when: swapfile|failed and write_swapfile.changed
  command: mkswap {{ swap_file }}

- name: enable swap
  when: swapfile|failed
  command: swapon {{ swap_file }}

- name: add swapfile mount point
  when: swapfile|failed
  mount: >
    name=none
    src="{{ swap_file }}"
    fstype=swap
    opts=sw
    passno=0
    dump=0
    state=present

- name: set swappiness
  when: swapfile|failed
  sysctl: name=vm.swappiness
          value={{ swapfile_swappiness | default('1') }}
          state=present

- name: set vfs cache pressure
  when: swapfile|failed
  sysctl: name=vm.vfs_cache_pressure
          value={{ swapfile_vfs_cache_pressure | default('50') }}
          state=present
