- name: security limits
  template: src=limits.conf.j2 dest=/etc/security/limits.conf owner=root group=root mode=0440

- name: install utils
  apt: name="{{ item }}" state=present
  with_items:
    - tmux
    - htop
    - vim
    - git
    - xfsprogs

- name: use vim by default
  alternatives: name=editor path=/usr/bin/vim.basic link=/etc/alternatives/editor
